In [156]:
import numpy as np

# A)

A = np.matrix('0 1 2; 1 2 0')

AtA = np.matmul(A.T, A)
AAt = np.matmul(A, A.T)

print(AtA)
print(AAt)

#Symmetrie
print(AAt == AAt.T)
print(AtA == AtA.T)

[[1 2 0]
 [2 5 2]
 [0 2 4]]
[[5 2]
 [2 5]]
[[ True  True]
 [ True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [157]:
# B)

# A-lambda*I
#identity = np.identity(3)
# print(np.subtract(AtA, l*identity))  Wie Matrix mit Variable multiplizieren?

In [158]:
eigenwerte = np.linalg.eigvals(AtA)
print(eigenwerte)

[ 7.00000000e+00 -5.55111512e-16  3.00000000e+00]


In [159]:
eigenvektoren = np.linalg.eig(AtA)
print(eigenvektoren)

# für C)
lambda1 = eigenvektoren[0][0]
lambda2 = eigenvektoren[0][2]

eingenvektor_zu_lambda1 = eigenvektoren[1][0]
eingenvektor_zu_lambda2 = eigenvektoren[1][2]

print(lambda1)
print(lambda2)

(array([ 7.00000000e+00, -5.55111512e-16,  3.00000000e+00]), matrix([[-0.26726124,  0.87287156, -0.40824829],
        [-0.80178373, -0.43643578, -0.40824829],
        [-0.53452248,  0.21821789,  0.81649658]]))
6.999999999999996
3.0


In [1]:
length = np.sqrt(np.square(eigenvektoren[1].item(0, 0)) + np.square(eigenvektoren[1].item(0, 1)) + np.square(eigenvektoren[1].item(0, 2)))
print(length)

#Schon normiert

NameError: name 'np' is not defined

In [166]:
# C)



l1_vertikal = np.matrix(f'{eingenvektor_zu_lambda1.item(0)}; {eingenvektor_zu_lambda1.item(1)}; {eingenvektor_zu_lambda1.item(2)}')
l2_vertikal = np.matrix(f'{eingenvektor_zu_lambda2.item(0)}; {eingenvektor_zu_lambda2.item(1)}; {eingenvektor_zu_lambda2.item(2)}')

# print(l1_vertikal)
# print(l2_vertikal)
#
# print(A)


u1 = (1/np.sqrt(lambda1)) * (np.matmul(A, l1_vertikal))
u2 = (1/np.sqrt(lambda2)) * (np.matmul(A, l2_vertikal))

#
# print(u1)
# print(u2)

In [167]:
#Eigenvektor = Av = lamda v

print(np.matmul(AAt, u1))


print(np.multiply(lambda1, u1))

[[3.42431347]
 [1.21401757]]
[[ 4.89784407]
 [-0.25951302]]
