In [118]:
import numpy as np

# A)

A = np.matrix('0 1 2; 1 2 0')

AtA = np.matmul(A.T, A)
AAt = np.matmul(A, A.T)

print(AtA)
print(AAt)

#Symmetrie
print(AAt == AAt.T)
print(AtA == AtA.T)

[[1 2 0]
 [2 5 2]
 [0 2 4]]
[[5 2]
 [2 5]]
[[ True  True]
 [ True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [119]:
eigenwerte = np.linalg.eigvals(AtA)
print(eigenwerte)

[ 7.00000000e+00 -5.55111512e-16  3.00000000e+00]


In [120]:
#manuell ausrechnen:
# B)

# A-lambda*I
#identity = np.identity(3)
# print(np.subtract(AtA, l*identity))  Wie Matrix mit Variable multiplizieren?

#######


In [121]:
eigenvalues, eigenvectors = np.linalg.eig(AtA)

l1 = eigenvalues[0]
l2 = eigenvalues[2]
l3 = eigenvalues[1]

v1 = eigenvectors[:, 0]
v2 = eigenvectors[:, 2]
v3 = eigenvectors[:, 1]


In [122]:

length_v1 = np.sqrt(
    np.square(v1.item(0)) +
    np.square(v1.item(1)) +
    np.square(v1.item(2))
)

print(length_v1)

# => schon normiert

1.0


In [123]:
u1 = (1/np.sqrt(l1)) * np.matmul(A, v1)
u2 = (1/np.sqrt(l2)) * np.matmul(A, v2)

print(u1)
print(u2)

[[-0.70710678]
 [-0.70710678]]
[[ 0.70710678]
 [-0.70710678]]


In [124]:
# A v = lamda v

print(np.isclose( np.matmul(AAt, u1), (l1 * u1)) )
print(np.isclose( np.matmul(AAt, u2), (l2 * u2)) )

# => sind eigenvektoren

[[ True]
 [ True]]
[[ True]
 [ True]]


In [125]:
V = np.mat(f'{v1.item(0)} {v2.item(0)} {v3.item(0)};'
           f'{v1.item(1)} {v2.item(1)} {v3.item(1)};'
           f'{v1.item(2)} {v2.item(2)} {v3.item(2)}')
print("V in first")
print(V)

U = np.mat(f'{u1.item(0)} {u2.item(0)};'
           f'{u1.item(1)} {u2.item(1)}')

print("U in first")
print(U)


V in first
[[-0.26726124 -0.40824829  0.87287156]
 [-0.80178373 -0.40824829 -0.43643578]
 [-0.53452248  0.81649658  0.21821789]]
U in first
[[-0.70710678  0.70710678]
 [-0.70710678 -0.70710678]]


In [126]:
# d)

# Orthogonal = AT = A-1

print(np.isclose(V.T, np.linalg.inv(V)))

print(np.isclose(U.T, np.linalg.inv(U)))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True]
 [ True  True]]


In [131]:
# e)

Vv = np.diag([l1 ,l2, l3])

print(np.isclose(AtA, V @ Vv @ V.T))

Uv = np.diag([l1, l2])

print(np.isclose(AAt, U @ Uv @ U.T))


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True]
 [ True  True]]


In [135]:
# f)

S = np.mat(f'{np.sqrt(l1)} 0 0;'
           f'0 {np.sqrt(l2)} 0')


print(np.isclose(A, U @ S @ V.T ))


[[ True  True  True]
 [ True  True  True]]
